### ISSUE TITLE
properties aren't read from file when in classpath

### ISSUE THREAD

**Issue by ingenthr** [avsej/couchbase-kafka-hadoop-demo#3]
I couldn't get the properties to be read at first, even when in the classpath.  Perhaps this is because it has a leading slash?

It worked after I just gave it as an argument.

fails:
java -cp couchbase-kafka-hadoop-demo-1.0-all.jar:click_stream
_example.properties:. example.ClickStreamConsumer

works:
java -cp couchbase-kafka-hadoop-demo-1.0-all.jar:click_stream
_example.properties:. example.ClickStreamConsumer click_stream_example.properti
es

**Comment by avsej** [comment]
```
java -cp .:couchbase-kafka-hadoop-demo-1.0-all.jar example.ClickStreamProducer
```
